# Generated by Django 4.2.3 on 2023-07-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
