# Generated by Django 4.2.3 on 2023-07-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_service_image_service_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='service',
            name='introduction',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
