# Generated by Django 4.2.3 on 2024-01-25 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
