# Generated by Django 4.2.3 on 2023-07-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='content',
        ),
    ]
