# Generated by Django 4.2.3 on 2023-07-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_description_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
