# Generated by Django 4.2.3 on 2023-07-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_skill_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='job',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
