# Generated by Django 4.2.3 on 2023-07-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_testimonial_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.URLField(blank=True, null=True),
        ),
    ]
